### ISSUE TITLE
Using plugin with kotlin DSL

### ISSUE THREAD

**Issue by huehnerlady** [IntershopCommunicationsAG/jaxb-gradle-plugin#21]
Hi,

Are there examples how to use this plugin with the gradle kotlin DSL?

Many thanks

**Comment by m-raab** [comment]
Unfortunately there are no examples, but the plugin is prepared. I think the DSL should work also for kts.

**Comment by huehnerlady** [comment]
when use the example I get the following error:
`build.gradle.kts:39:9: Unresolved reference: schema`

code:
```
tasks{
jaxb {
    javaGen {
      posConfig {
        packageName = ""
        schema = file("pos.xsd")
      }
    }
  }
}
```

**Comment by martinsefcik** [comment]
@huehnerlady  this is working at least for 3.0.2
`jaxb {
    javaGen {
        create("payment") {
            setSchema(file("src/test/resources/schemas/payment.xsd"))
            setBinding(file("src/test/resources/xjb/payment-bindings.xjb"))

            packageName = "com.package.name"
            extension = true
        }
    }
}`
