### ISSUE TITLE
Issues after

### ISSUE THREAD

**Issue by Samyssmile** [IntershopCommunicationsAG/jaxb-gradle-plugin#41]
Hi, I want to update my Project from jaxb plugin 2.0 step by step to 4.

Actually I updated it to 3.0.0, now on "gradle jaxb" task. I getting this Exception.

` java.lang.IllegalArgumentException: Cannot get the value of a property of type java.util.List with element type java.lang.String as the source value contains an element of type java.io.File.`

Gradle: 5.6.3
Java 8
Plugin: "com.intershop.gradle.jaxb:jaxb-gradle-plugin:3.0.0"

Any Idea how to fix it?

**Comment by thetric** [comment]
Could you please show the relevant sections of your `build.gradle`?
