### ISSUE TITLE
Java 8: accessExternalSchema not defined

### ISSUE THREAD

**Issue by robertoschwald** [IntershopCommunicationsAG/jaxb-gradle-plugin#5]
In Java 8, XJC cannot read the schema file, as accessExternalSchema settings restricts it. 

With -Djavax.xml.accessExternalSchema=all, this would be allowed. 

Workaround: 

Before the jaxb block in build.gradle, set:
```groovy
System.setProperty('javax.xml.accessExternalSchema', 'file')
```

**Comment by robertoschwald** [comment]
Closed without comment?

**Comment by m-raab** [comment]
There is unfortunatelly no better solution and I the plugin can not add this configuration.

**Comment by robertoschwald** [comment]
So something in the readme is needed imho.

**Comment by boris-petrov** [comment]
@robertoschwald - I have another issue (https://github.com/IntershopCommunicationsAG/jaxb-gradle-plugin/issues/9) - but this workaround doesn't help. It's funny that I have no problems with Java 8 but rather with XJC's version. Do you happen to have any ideas?
