### ISSUE TITLE
build with debug parameter generates a JAXBDebug class for all configurations

### ISSUE THREAD

**Issue by m-raab** [IntershopCommunicationsAG/jaxb-gradle-plugin#7]
Builds with more than one configuration fails with a compile error, because there are duplicated classes.

**Comment by dalewking** [comment]
Ran into this myself as well

**Comment by m-raab** [comment]
The generated code contains always some classes with the same name. For each configuration an output directory is created. During the compilation all source directories are used, therefore it is necessary to specify different package names for each configuration.
